# Generated by Django 5.2.3 on 2025-06-19 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='foto_product',
            field=models.URLField(max_length=600),
        ),
    ]
