# Generated by Django 5.2.3 on 2025-06-19 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_product_foto_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='harga',
            name='tipe_harga',
            field=models.CharField(choices=[('Harga pabrik', 'Harga pabrik'), ('Harga ke pasar', 'Harga ke pasar'), ('Harga di pasar', 'Harga di pasar'), ('Harga ke toko', 'Harga ke toko'), ('Harga di toko', 'Harga di toko')], max_length=20),
        ),
    ]
