# Generated by Django 5.2.3 on 2025-07-01 06:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_harga_tipe_harga'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('quantity', models.IntegerField(default=0)),
                ('product_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='product.product')),
            ],
        ),
    ]
