# Generated by Django 5.2.3 on 2025-07-01 08:27

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pt', models.CharField(max_length=20)),
                ('nama', models.CharField(max_length=20)),
                ('alamat', models.CharField(max_length=50)),
                ('telepon', models.CharField(max_length=13)),
                ('is_aktif', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='stock',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stock',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='ProductInSuplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('jumlah_belanja', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tanggal_belanja', models.DateField(auto_now_add=True)),
                ('quantity', models.IntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_list', to='product.product')),
                ('suplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suplier_list', to='product.suplier')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
