# Generated by Django 5.2.3 on 2025-07-17 07:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_suplier_stock_created_at_stock_updated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Belanja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_belanja', models.DateField(auto_now_add=True)),
                ('suplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.suplier')),
            ],
        ),
        migrations.CreateModel(
            name='ItemBelanja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah_belanja', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.IntegerField()),
                ('belanja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='product.belanja')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
        ),
    ]
