# Generated by Django 5.2.3 on 2025-07-18 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_belanja_itembelanja'),
    ]

    operations = [
        migrations.AddField(
            model_name='belanja',
            name='total_belanja',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='harga',
            name='tipe_harga',
            field=models.CharField(choices=[('Harga pabrik', 'Harga pabrik'), ('Harga ke pasar', 'Harga ke pasar'), ('Harga di pasar', 'Harga di pasar'), ('Harga ke toko', 'Harga ke toko'), ('Harga di toko', 'Harga di toko'), ('Harga BS', 'Harga BS'), ('Harga Ecer', 'Harga Ecer')], max_length=20),
        ),
    ]
