# Generated by Django 5.2.3 on 2025-08-05 09:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_belanja_total_belanja_alter_harga_tipe_harga'),
        ('toko', '0006_jalur_users'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TransaksiPengambilan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tanggal_ambil', models.DateField(auto_now_add=True)),
                ('total_nilai', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('dikonfirmasi', 'Dikonfirmasi'), ('dibatalkan', 'Dibatalkan')], default='draft', max_length=20)),
                ('catatan', models.TextField(blank=True, null=True)),
                ('jalur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaksi_pengambilan', to='toko.jalur')),
                ('sales', models.ForeignKey(help_text='User yang mengambil barang (harus sales)', on_delete=django.db.models.deletion.CASCADE, related_name='pengambilan_barang', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ItemPengambilan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.PositiveIntegerField()),
                ('harga_satuan', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
                ('transaksi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='product.transaksipengambilan')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
