# Generated by Django 5.2.3 on 2025-08-05 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_transaksipengambilan_itempengambilan'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaksipengambilan',
            name='tipe_harga',
            field=models.CharField(choices=[('Harga ke pasar', 'Harga ke pasar'), ('Harga ke toko', 'Harga ke toko')], default='Harga ke toko', max_length=20),
        ),
        migrations.AlterField(
            model_name='itempengambilan',
            name='harga_satuan',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
