# Generated by Django 5.2.3 on 2025-08-05 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_transaksipengambilan_tipe_harga_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaksipengambilan',
            name='jalur',
        ),
        migrations.RemoveField(
            model_name='transaksipengambilan',
            name='sales',
        ),
        migrations.DeleteModel(
            name='ItemPengambilan',
        ),
        migrations.DeleteModel(
            name='TransaksiPengambilan',
        ),
    ]
