# Generated by Django 5.2.3 on 2025-08-06 13:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_transaksipengambilan_itempengambilan'),
        ('toko', '0006_jalur_users'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TransaksiPembayaran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_pembayaran', models.DateField(auto_now_add=True)),
                ('total_pengambilan', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('jumlah_dibayar', models.DecimalField(decimal_places=2, max_digits=12)),
                ('kekurangan_bayar', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status_pembayaran', models.CharField(choices=[('belum dibayar', 'Belum Dibayar'), ('belum lunas', 'Belum Lunas'), ('lunas', 'Lunas')], default='belum dibayar', max_length=20)),
                ('jalur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='toko.jalur')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ItemPembayaran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('tipe_harga', models.CharField(max_length=50)),
                ('harga_satuan', models.DecimalField(decimal_places=2, max_digits=12)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('item_pengambilan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.itempengambilan')),
                ('transaksi_pembayaran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='product.transaksipembayaran')),
            ],
        ),
    ]
