# Generated by Django 5.2.3 on 2025-08-06 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_transaksipembayaran_itempembayaran'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itempembayaran',
            name='tipe_harga',
        ),
    ]
