# Generated by Django 5.2.3 on 2025-08-16 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_remove_itempembayaran_tipe_harga'),
    ]

    operations = [
        migrations.AlterField(
            model_name='harga',
            name='tipe_harga',
            field=models.CharField(choices=[('Harga pabrik', 'Harga pabrik'), ('Harga ke pasar', 'Harga ke pasar'), ('Harga di pasar', 'Harga di pasar'), ('Harga ke toko', 'Harga ke toko'), ('Harga di toko', 'Harga di toko'), ('Harga BS pasar', 'Harga BS pasar'), ('Harga BS toko', 'Harga BS toko'), ('Harga Ecer', 'Harga Ecer')], max_length=20),
        ),
    ]
