# Generated by Django 5.2.3 on 2025-09-17 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_alter_harga_tipe_harga'),
    ]

    operations = [
        migrations.AddField(
            model_name='itempengambilan',
            name='tipe_item',
            field=models.CharField(choices=[('normal', 'Normal'), ('bs', 'Barang Sisa'), ('retur', 'Retur')], default='normal', max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='harga',
            unique_together={('product', 'tipe_harga')},
        ),
    ]
