# Generated by Django 5.2.3 on 2025-06-19 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='toko',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=20)),
                ('alamat', models.CharField(max_length=50)),
                ('koordinat', models.CharField(max_length=100)),
                ('telepon', models.CharField(max_length=13)),
                ('is_pasar', models.BooleanField(default=False)),
            ],
        ),
    ]
