# Generated by Django 5.2.3 on 2025-07-04 07:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toko', '0002_toko_created_at_toko_is_delete_toko_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jalur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='toko',
            name='jalur',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='toko_list', to='toko.jalur'),
            preserve_default=False,
        ),
    ]
