# Generated by Django 5.2.3 on 2025-08-04 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toko', '0004_jalur_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jalur',
            name='user',
        ),
    ]
